language: go

# Versions of go that are explicitly supported.
go:
 - 1.5.4
 - 1.6.3
 - 1.7

# Required for coverage.
before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls
